/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as labelRouteRouteImport } from './routes/(label)/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as labelLabelIdRouteImport } from './routes/(label)/$labelId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const labelRouteRoute = labelRouteRouteImport.update({
  id: '/(label)',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const labelLabelIdRoute = labelLabelIdRouteImport.update({
  id: '/$labelId',
  path: '/$labelId',
  getParentRoute: () => labelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof labelRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/$labelId': typeof labelLabelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof labelRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/$labelId': typeof labelLabelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/(label)': typeof labelRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/(label)/$labelId': typeof labelLabelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/$labelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/$labelId'
  id: '__root__' | '/' | '/(label)' | '/projects' | '/(label)/$labelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  labelRouteRoute: typeof labelRouteRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(label)': {
      id: '/(label)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof labelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(label)/$labelId': {
      id: '/(label)/$labelId'
      path: '/$labelId'
      fullPath: '/$labelId'
      preLoaderRoute: typeof labelLabelIdRouteImport
      parentRoute: typeof labelRouteRoute
    }
  }
}

interface labelRouteRouteChildren {
  labelLabelIdRoute: typeof labelLabelIdRoute
}

const labelRouteRouteChildren: labelRouteRouteChildren = {
  labelLabelIdRoute: labelLabelIdRoute,
}

const labelRouteRouteWithChildren = labelRouteRoute._addFileChildren(
  labelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  labelRouteRoute: labelRouteRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
